@endpoint = http://localhost:5050/api/v1/cars

 

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "make" : "Mercedes",
  "model" : "E-Class"
}

###

@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0 
content-type: application/json
x-api-key: blahblah 

 

### 

GET  {{endpoint}}/{{newCar}} HTTP/3.0 
content-type: application/json
### 

 

DELETE  {{endpoint}}/id HTTP/3.0 
content-type: application/json 

 

### 

 

###
PUT {{endpoint}}/sillycarID HTTP/1.1

Content-Type: application/json

{
    "name": "red vroom vroom"
}