@endpoint = http://localhost:5050/api/v1/cars

### 

POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "model": "Toyota",
    "make": "Corolla"
}

 

 

###
GET  {{endpoint}} HTTP/3.0 
content-type: application/json 

 

### 

GET  {{endpoint}}/sillycarID HTTP/3.0 
content-type: application/json
### 

 

DELETE  {{endpoint}}/idHere HTTP/3.0 
content-type: application/json 

 

### 

 

###
PUT {{endpoint}}/sillycarID HTTP/1.1

Content-Type: application/json

{
    "name": "red vroom vroom"
}